### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by m00nfly** [machengim/oasis#6]
在 FreeBSD 12.2 下源代码编译失败，有如下报错

编译环境：rust-1.55.0   node-16.10

   Compiling include_dir v0.6.2
   Compiling devise_codegen v0.3.1
   Compiling tempfile v3.2.0
   Compiling pear v0.2.3
   Compiling futures-executor v0.3.16
   Compiling tokio-util v0.6.7
   Compiling tokio-rustls v0.22.0
   Compiling tokio-stream v0.1.7
error[E0308]: mismatched types
  --> /root/.cargo/registry/src/github.com-1285ae84e5963aae/local-ip-address-0.4.4/src/lib.rs:86:22
   |
86 | pub fn local_ip() -> Result<IpAddr, Error> {
   |        --------      ^^^^^^^^^^^^^^^^^^^^^ expected enum `Result`, found `()`
   |        |
   |        implicitly returns `()` as its body has no tail or `return` expression
   |
   = note:   expected enum `Result<IpAddr, Error>`
           found unit type `()`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `local-ip-address` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed

    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at runCommand (/root/oasis/build.js:23:17)
    at Object.<anonymous> (/root/oasis/build.js:48:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  status: 101,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(11937) [Uint8Array] [
       32,  32,  32,  32,  85, 112, 100,  97, 116, 105, 110, 103,
       32,  99, 114,  97, 116, 101, 115,  46, 105, 111,  32, 105,
      110, 100, 101, 120,  10,  32,  68, 111, 119, 110, 108, 111,
       97, 100, 105, 110, 103,  32,  99, 114,  97, 116, 101, 115,
       32,  46,  46,  46,  10,  32,  32,  68, 111, 119, 110, 108,
      111,  97, 100, 101, 100,  32,  97, 117, 116, 111,  99, 102,
      103,  32, 118,  49,  46,  48,  46,  49,  10,  32,  32,  68,
      111, 119, 110, 108, 111,  97, 100, 101, 100,  32, 116, 105,
      109, 101,  45, 109,
      ... 11837 more items
    ]
  ],
  pid: 790,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(11937) [Uint8Array] [
     32,  32,  32,  32,  85, 112, 100,  97, 116, 105, 110, 103,
     32,  99, 114,  97, 116, 101, 115,  46, 105, 111,  32, 105,
    110, 100, 101, 120,  10,  32,  68, 111, 119, 110, 108, 111,
     97, 100, 105, 110, 103,  32,  99, 114,  97, 116, 101, 115,
     32,  46,  46,  46,  10,  32,  32,  68, 111, 119, 110, 108,
    111,  97, 100, 101, 100,  32,  97, 117, 116, 111,  99, 102,
    103,  32, 118,  49,  46,  48,  46,  49,  10,  32,  32,  68,
    111, 119, 110, 108, 111,  97, 100, 101, 100,  32, 116, 105,
    109, 101,  45, 109,
    ... 11837 more items
  ]
}

**Comment by machengim** [comment]
应该是 local-ip-address 库不支持freebsd。可能会考虑用别的库解决这个问题。

**Comment by machengim** [comment]
或许可以先使用docker版？
